### ISSUE TITLE
Retro, Discuss, Action (Nov 1- Nov 15)

### ISSUE THREAD

**Issue by leojkwan** [superfit-athletics/android#16]
## Agenda
- How is the start of this project going?
- What is going well?
- What are some learnings that we can take to next block?

## Discuss
- #9 
- Now that @sufeiiz is a bit more acquainted with SuperFit's workout application, models, and overall domain exposure, Let's double down on getting Program Catalogs information presented and transformed into a "Program". I will create a document on this as the process is a bit longwinded, and unvisited since I first initially built the functionality on iOS

## Action (Nov 1- Nov 15)
- TBD
- Add documentation on posting and fetching a "Program"

**Comment by leojkwan** [comment]
Hey Sufei,

I am going to write a doc about Program Catalogs and how they need to generate a "Program" model on the client.

Warning: I've made some decisions that may not be the best moving forward, but since we're both the full stack engs to this project, we can dictate how to move forward together.

STAY TUNED.

**Comment by leojkwan** [comment]
I think the next two weeks of dev work should be focused on our Program Catalog Search experience

https://superfitapp.quip.com/SDCtAb9hCDkG.

Persistence can be introduced at the tail end of the feature, but I think the main gist is to get the search UI flow and detail UI flow nailed down. I will add a video that highlights the UI with more precision soon.

**Comment by leojkwan** [comment]
@sufeiiz I can start adding tickets, but if you have a preference for how to best tackle this story, feel free to add the issues on your own in our GitHub project board.

**Comment by leojkwan** [comment]
Re: #9 adding logging is fine with me in these two weeks, I just had a question in the issue before we close it.

**Comment by sufeiiz** [comment]
How is the start of this project going? **I feel good about the progress we've made so far. The necessary dependencies are in and we can start building the UI now. I do find it hard focus when I try to work on this on weekdays, but that's something I'm working on. I also don't know what information I need/what questions I should be asking until I start on it, and since we work different hours sometimes there's a delay and I'm blocked from starting. I also still don't feel fully familiar with the product itself, and it would help once I have an iOS build to play with.**
What is going well? **We communicate really well. You've been great in providing me with docs.**
What are some learnings that we can take to next block? **We should clarify our roadmap now that the bones of the app are done. Mainly, what should I prioritize and how can we communicate about design decisions on here or quip? Also, is this when you would like to get into the codebase and take on a simple task?**

**Comment by leojkwan** [comment]
Hey Sufei,

I feel good about the progress made too. Grab an iOS device and play around with the app- no better way than to experiencing the application in your hands!

This is definitely where I can jump in and take on rote tasks like porting over our data models and these Daos you've made for Room.

I think the biggest prioritization now is the “Program Catalog” milestone on Github It does not require any other models that we haven't mentioned in order to build that UI component out. The persistence level will need to be added but you have the option of focusing on that portion after you get an even better feel for †he business logic and catalog models.

Glad you think we communicate well!

We can communicate on both Quip or Github. I propose can use Github for code related discussions like code issue management. However, *anything* wiki-like or product-related should live in Quip. I just think it's better as a living document where everything business, engineering, product, marketing, can live in one central place.I personally like the inline commenting and collaboration so I can contribute to any documents you add here!

Thanks for answering those questions @sufeiiz
